spring.application.name=ecomp-web-app
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
spring.jpa.hibernate.ddi-auto=create
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=MyEcomApp
info.app.version=1.0.0
info.app.description=App Built by me
management.endpoint.shutdown.enabled=true
server.shutdown=graceful

